- name: Setup SSH Agent
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        echo "$SSH_KEY_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

    - name: Deploy to DigitalOcean Droplet
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        REGISTRY: registry.digitalocean.com/newprojectsuperapp
        IMAGE_NAME: super-new-project
      run: |
        ssh -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "
          docker pull $REGISTRY/$IMAGE_NAME:${{ github.sha }} &&
          docker stop $IMAGE_NAME || true &&
          docker rm $IMAGE_NAME || true &&
          docker run -d --name $IMAGE_NAME -p 80:80 $REGISTRY/$IMAGE_NAME:${{ github.sha }}
        "
