name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: zoeemmanuel/super_new_project:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main-branch

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./master-branch
          file: ./master-branch/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Verify SSH Configuration
        run: |
          echo "Checking SSH key..."
          if [ -n "${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}" ]; then
            echo "SSH private key is set"
            echo "First few characters of the key: ${${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}:0:10}..."
          else
            echo "SSH private key is not set"
          fi

          echo "Checking SSH passphrase..."
          if [ -n "${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}" ]; then
            echo "SSH passphrase is set"
            echo "Length of passphrase: ${#${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}}"
          else
            echo "SSH passphrase is not set"
          fi

          echo "Checking DigitalOcean host..."
          if [ -n "${{ secrets.DIGITALOCEAN_HOST }}" ]; then
            echo "DigitalOcean host is set"
            echo "Host: ${{ secrets.DIGITALOCEAN_HOST }}"
          else
            echo "DigitalOcean host is not set"
          fi

          echo "Checking SSH user..."
          if [ -n "${{ secrets.DIGITALOCEAN_SSH_USER }}" ]; then
            echo "SSH user is set"
            echo "User: ${{ secrets.DIGITALOCEAN_SSH_USER }}"
          else
            echo "SSH user is not set"
          fi

      - name: Debug SSH connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "SSH connection successful"
            whoami
            pwd
            ls -la

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}
            docker stop super_new_project || true
            docker rm super_new_project || true
            docker run -d --name super_new_project -p 80:80 ${{ env.DOCKER_IMAGE }}

      - name: Check container status
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker ps
            docker logs super_new_project
