name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ master ]  # Changed from 'main' to 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
          docker stop super_new_project || true
          docker rm super_new_project || true
          docker run -d --name super_new_project -p 80:80 ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
