name: Docker Build, Push, and Deploy to DigitalOcean
on:
  push:
    branches: [ master ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Build and push
      env:
        REGISTRY: registry.digitalocean.com/newprojectsuperapp
        IMAGE_NAME: super-new-project
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
        docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
    - name: Deploy to DigitalOcean Droplet
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        REGISTRY: registry.digitalocean.com/newprojectsuperapp
        IMAGE_NAME: super-new-project
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST} "
          docker pull $REGISTRY/$IMAGE_NAME:${{ github.sha }} &&
          docker stop $IMAGE_NAME || true &&
          docker rm $IMAGE_NAME || true &&
          docker run -d --name $IMAGE_NAME -p 80:80 $REGISTRY/$IMAGE_NAME:${{ github.sha }}
        "
