- name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
        script: |
          echo "Connected successfully"
          docker --version
          docker pull ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
          docker stop super_new_project || true
          docker rm super_new_project || true
          docker run -d --name super_new_project -p 80:80 ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
        debug: true
