name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: zoeemmanuel/super_new_project:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main-branch

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./master-branch
          file: ./master-branch/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}


      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}
            docker stop super_new_project || true
            docker rm super_new_project || true
            docker run -d --name super_new_project -p 80:80 ${{ env.DOCKER_IMAGE }}

      - name: Check container status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          script: |
            docker ps
            docker logs super_new_project
