name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Make sure this matches your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust this to match your project's Node.js version

    - name: Install dependencies
      run: npm ci  # This uses package-lock.json for a clean install

    - name: Build project
      run: npm run build  # Make sure this script is defined in your package.json

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
          docker stop super_new_project || true
          docker rm super_new_project || true
          docker run -d --name super_new_project -p 80:80 ${{ secrets.DOCKER_USERNAME }}/super_new_project:latest
