name: Debug SSH Connection to DigitalOcean
on:
  push:
    branches: [ master ]
jobs:
  debug-ssh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SSH Debug Environment
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        echo "Private key fingerprint:"
        ssh-keygen -l -f ~/.ssh/id_rsa
        echo "Public key:"
        cat ~/.ssh/id_rsa.pub
        
    - name: Attempt SSH Connection
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
      run: |
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        ssh -v -i ~/.ssh/id_rsa ${USERNAME}@${HOST} "echo 'SSH connection successful'"

    - name: Check SSH Debug Output
      if: failure()
      run: |
        echo "SSH connection failed. Please check the verbose output above for more details."
        echo "Ensure that the public key is properly added to authorized_keys on the DigitalOcean droplet."
