name: SSH Debug Info
on:
  push:
    branches: [ master ]
jobs:
  ssh-debug-info:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH environment
      env:
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Display SSH key info
      run: |
        echo "Private key file contents (first and last lines):"
        sed -n '1p; $p' ~/.ssh/id_rsa
        
        echo "Private key permissions:"
        ls -l ~/.ssh/id_rsa
        
        echo "Private key details:"
        ssh-keygen -l -f ~/.ssh/id_rsa
        
        echo "Corresponding public key:"
        ssh-keygen -y -f ~/.ssh/id_rsa
        
    - name: Display SSH config
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USERNAME: ${{ secrets.DIGITALOCEAN_SSH_USER }}
      run: |
        echo "SSH connection command that would be used:"
        echo "ssh -i ~/.ssh/id_rsa ${USERNAME}@${HOST}"
        
        echo "SSH client version:"
        ssh -V
        
    - name: Check SSH known hosts
      env:
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
      run: |
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        echo "Known hosts entry for $HOST:"
        grep $HOST ~/.ssh/known_hosts

    - name: Display environment info
      run: |
        echo "GitHub Actions runner OS:"
        uname -a
        
        echo "OpenSSH version:"
        ssh -V 2>&1

    - name: Suggestion for next steps
      run: |
        echo "Based on the information above, please verify the following:"
        echo "1. The private key in the DIGITALOCEAN_SSH_PRIVATE_KEY secret starts with '-----BEGIN OPENSSH PRIVATE KEY-----' and ends with '-----END OPENSSH PRIVATE KEY-----'"
        echo "2. The public key displayed matches the one in your DigitalOcean droplet's ~/.ssh/authorized_keys file"
        echo "3. The USERNAME (${USERNAME}) and HOST (${HOST}) are correct for your DigitalOcean droplet"
        echo "4. The user specified by USERNAME has the necessary permissions on the droplet"
        echo "5. Your DigitalOcean droplet's firewall allows SSH connections from GitHub Actions IP ranges"
