name: Docker Build and Push to DigitalOcean

on:
  push:
    branches: [ master ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.digitalocean.com/newprojectsuperapp/${{ secrets.DO_IMAGE_NAME }}:$(date +%s)

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/newprojectsuperapp/${{ secrets.DO_IMAGE_NAME }}:$(date +%s)
