name: Sync main to master

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "master"
          pr_title: "Sync: Main to Master"
          pr_body: "Automated PR to sync changes from main to master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
